### ISSUE TITLE
Installation is broken due to broken nan package

### ISSUE THREAD

**Issue by tomers** [vue-generators/vue-form-generator#457]
*** This issue has a workaround. Please read below. ***

Cloning the repository and running `npm install` fails:
```
$ npm install

...

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:In file included from 6:
../fsevents.ccIn file included from :../../nan/nan.h6::
192In file included from :
../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112../../nan/nan_maybe_43_inl.h::15112:: 15: error: error: no nomember  membernamed  named'ForceSet'  'ForceSet'in  in'v8::Object' 'v8::Object'

...

make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/toshalev/git/temp/temp1/vue-form-generator/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/10.2.1/bin/node" "/Users/toshalev/git/temp/temp1/vue-form-generator/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/toshalev/git/temp/temp1/vue-form-generator/node_modules/node-sass
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
```

The issue is similar to the issue found in other projects, e.g. https://github.com/justadudewhohacks/opencv4nodejs/issues/295

# RESOLUTION
This is a temporary resolution, until a newer release of the `nan` package is made.
Replace `nan` package with the HEAD of the Github repo:
```
$ git diff package.json 
diff --git a/package.json b/package.json
index c9335fa..4a98b47 100644
--- a/package.json
+++ b/package.json
@@ -85,6 +85,7 @@
     "mocha": "2.5.3",
     "mocha-generators": "1.2.0",
     "mocha-loader": "0.7.1",
+    "nan": "git+https://github.com/nodejs/nan.git",
     "node-sass": "4.7.2",
     "phantomjs-prebuilt": "2.1.14",
     "pug": "2.0.0-beta11",
```

**Comment by tomers** [comment]
Dependency graph for the `nan` package:
```
$ npm ls nan
vue-form-generator@2.2.2 /Users/toshalev/git/temp/vue-form-generator
└─┬ karma@1.4.1
  └─┬ chokidar@1.7.0
    └─┬ UNMET OPTIONAL DEPENDENCY fsevents@1.1.3
      └── nan@2.10.0  deduped (git+https://github.com/nodejs/nan.git#77d0fcaba3305d05176a9ad95d8e5101e8f2a283)
```

**Comment by qkdreyer** [comment]
Thanks for the workaround !

**Comment by qkdreyer** [comment]
Upgrading node-sass to 4.9.0 is also resolving the issue
